[Settings]
; All values are in milliseconds.
; 1000 ms = 1 second.

; BUSTED
BustedTextMs=1000
BustedFadeStartMs=500
BustedFadeWindowMs=500
BustedFinishMs=1000

; WASTED
WastedTextMs=1000
WastedFadeStartMs=500
WastedFadeWindowMs=500
